iri: 8ed7eba8-5abf-4f08-8b86-6bbf696a0b9e
projectIri: 8ed7eba8-5abf-4f08-8b86-6bbf696a0b9e
types:
  - http://dataspecer.com/resources/local/package
userMetadata:
  label:
    cs: bb
    en: :)
  description: {}
metadata:
  creationDate: 2026-03-15T13:50:50.466Z
  modificationDate: 2026-03-15T16:14:00.350Z
_version: 1
_exportVersion: 2
_exportedAt: 2026-03-15T16:14:10.441Z
_exportedBy: http://localhost:3100
